"""Differential test: an ONNX model through the real compiler vs. ONNX's
own reference implementation.

This is docs/roadmap.md M2's last box. Everything else in this repository
that claims the compiler computes the right answer starts from MLIR that
this repository wrote -- hand-written in the FileCheck tests, generated by
a string builder in the two differential tests. This one starts from a
model file in a format defined by other people, and checks the compiled
result against the implementation those same people ship as the
specification's reference.

WHICH PASSES THIS RUNS, AND WHY NOT ALL OF THEM
-----------------------------------------------
cim-detect, cim-partition and (where stated) cim-placement. NOT the full
eight-pass chain, and this is deliberate rather than an oversight:
cim-legalize-precision inserts a cim.requantize that clamps every
accumulator to the target's `precision.output_effective_bits`, which is 8
in every shipped target file. That is a real modeled hardware effect --
an 8-bit output really does clamp -- but it means the compiled result
stops matching an *unquantized* ONNX oracle the moment any accumulator
leaves [-128, 127], which is essentially always. Adding the missing five
passes here would look like an improvement and would produce a mysterious
failure.

THE TRANSPOSE IS THE RISK
-------------------------
ONNX stores the weight as [K, N]; cim.mvm wants output-major [N, K]. A
wrong transpose emits IR that passes every verifier and computes wrong
numbers, silently, whenever the weight is square. Three guards, in
increasing strength: rectangular shapes throughout (so a missing
transpose is a shape error, not a wrong answer), a direct assertion on
the emitted literal, and a mutation check proving that assertion has
teeth.
"""

import os
import re
import sys

import numpy as np
import pytest

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "python"))

onnx = pytest.importorskip("onnx", reason="the ONNX front end's oracle")

from cim_frontend.onnx_import import import_model, load_matmul_integer  # noqa: E402
from cim_frontend.refusal import Refusal  # noqa: E402
from onnx_fixtures import (matmul_integer_model, onnx_reference_eval,  # noqa: E402
                           onnxruntime_eval)
from test_numerical_differential import (TINY_TARGET, compile_and_run,  # noqa: E402
                                         PipelineError)

SEED = int(os.environ.get("CIM_TEST_SEED", "0x5eed1234abcd"), 0)

# (K, N) in ONNX's own layout. Against tiny-4x4's 2 tiles of 4x4 this
# covers a single block, N-tiled, K-tiled, both-tiled and
# more-blocks-than-tiles. Every entry is deliberately NON-SQUARE except
# the two that exist to prove the square case is covered too -- see the
# module docstring on the transpose.
SHAPES = [(4, 8), (8, 4), (4, 12), (12, 4), (8, 12), (4, 4), (8, 8)]


def _weights_and_act(k, n, seed):
    rng = np.random.default_rng(seed)
    # Asymmetric and sign-mixed on purpose: a symmetric weight matrix is
    # blind to transposition, and an all-zero activation is blind to the
    # weights entirely.
    weight = rng.integers(-127, 128, size=(k, n), dtype=np.int64).astype(np.int8)
    act = rng.integers(-127, 128, size=k, dtype=np.int64).astype(np.int8)
    return weight, act


def _emitted_weight(text):
    """Parse the [N, K] weight literal back out of emitted MLIR."""
    match = re.search(r"memref\.global[^=]*=\s*dense<\[(\[.*?\])\]>", text,
                      re.S)
    assert match, "no weight dense<> literal in the emitted module"
    rows = re.findall(r"\[([^\[\]]*)\]", match.group(1))
    return np.array([[int(v) for v in row.split(",")] for row in rows],
                    dtype=np.int64)


# ---------------------------------------------------------------------------
# The transpose, checked directly -- no compiler involved, so a failure
# names the transpose rather than naming "the pipeline".
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("k,n", SHAPES)
def test_emitted_weight_is_the_onnx_weight_transposed(k, n):
    weight, act = _weights_and_act(k, n, SEED)
    model = matmul_integer_model(weight)
    text = import_model(model, act)

    got = _emitted_weight(text)
    assert got.shape == (n, k), (
        f"emitted weight is {got.shape}, expected [N, K] = {(n, k)}")
    assert np.array_equal(got, weight.T.astype(np.int64)), (
        "the emitted weight is not the ONNX weight transposed; cim.mvm "
        "indexes W[n][k] while ONNX stores B[k][n]")


def test_the_transpose_check_would_catch_a_missing_transpose():
    # The mutation check for the check above. On a SQUARE, non-symmetric
    # weight a missing transpose is not a shape error, so if
    # test_emitted_weight_is_the_onnx_weight_transposed could ever pass
    # against an untransposed weight it would be worthless. Prove it
    # cannot: the transposed and untransposed forms genuinely differ.
    weight, act = _weights_and_act(6, 6, SEED)
    model = matmul_integer_model(weight)
    got = _emitted_weight(import_model(model, act))

    assert np.array_equal(got, weight.T.astype(np.int64))
    assert not np.array_equal(got, weight.astype(np.int64)), (
        "this fixture's weight is symmetric, so it cannot distinguish a "
        "correct transpose from a missing one -- pick different values")


# ---------------------------------------------------------------------------
# The headline: model file -> real compiler -> simulator, vs. ONNX's own
# reference implementation.
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("k,n", SHAPES)
@pytest.mark.parametrize("placement", [False, True])
def test_onnx_model_compiles_and_matches_the_reference(cim_opt, cim_run, k, n,
                                                        placement):
    weight, act = _weights_and_act(k, n, SEED + k * 100 + n)
    model = matmul_integer_model(weight)

    want = onnx_reference_eval(model, act)
    # int8 x int8 over K <= 12 cannot leave int32, so the simulator's
    # documented wraparound (simulator.cpp: a fixed-width accumulator
    # wraps, it does not saturate) is never reached and the two are
    # comparable. Assert the bound rather than trusting it.
    assert np.abs(want).max() < 2 ** 31

    text = import_model(model, act)
    try:
        outputs, _ = compile_and_run(cim_opt, cim_run, None, None,
                                     placement=placement, source=text)
    except PipelineError as err:
        pytest.fail(f"the imported model failed to compile or run: {err}")

    assert np.array_equal(np.asarray(outputs), want), (
        f"compiled output {list(outputs)} != ONNX reference "
        f"{want.tolist()} for K={k} N={n} placement={placement}")


def test_onnxruntime_agrees_with_the_onnx_reference(cim_opt, cim_run):
    # A second, independent oracle where it is available. onnxruntime is a
    # production engine rather than the spec's reference implementation,
    # and its quantized kernels are registered per dtype pair, so int8 x
    # int8 support is a property of the installed build. Treat an
    # exception as "not available", never as a failure.
    ort = pytest.importorskip("onnxruntime")
    del ort

    weight, act = _weights_and_act(8, 12, SEED)
    model = matmul_integer_model(weight)
    want = onnx_reference_eval(model, act)
    try:
        got = onnxruntime_eval(model, act)
    except Exception as err:  # noqa: BLE001 - any failure means "unsupported"
        pytest.skip(f"onnxruntime cannot run int8 x int8 MatMulInteger: {err}")

    assert np.array_equal(got, want), (
        "the two ONNX oracles disagree with each other, which means the test "
        "fixture is wrong rather than the compiler")

    outputs, _ = compile_and_run(cim_opt, cim_run, None, None,
                                 source=import_model(model, act))
    assert np.array_equal(np.asarray(outputs), want)


@pytest.mark.parametrize("m,k,n", [(3, 4, 8), (2, 8, 4), (4, 4, 4)])
@pytest.mark.parametrize("placement", [False, True])
def test_batched_activation_compiles_and_matches_the_reference(
        cim_opt, cim_run, m, k, n, placement):
    # M > 1: cim-partition tiles a real multi-row matmul into a generated
    # scf.for over the rows (docs/roadmap.md's M4 entry) instead of
    # refusing it, as it used to. Each row gets independently-sampled
    # values (not a broadcast constant) so a bug that let one row's
    # buffer leak into another's -- exactly the class of bug found and
    # fixed alongside this support, see CIMLowerToTarget.cpp's
    # hostPointer -- would produce a wrong, checkable number instead of a
    # lucky match.
    rng = np.random.default_rng(SEED + m * 10000 + k * 100 + n)
    weight = rng.integers(-127, 128, size=(k, n), dtype=np.int64).astype(np.int8)
    act = rng.integers(-127, 128, size=(m, k), dtype=np.int64).astype(np.int8)
    model = matmul_integer_model(weight, act_shape=[m, k])

    want = onnx_reference_eval(model, act)
    assert np.abs(want).max() < 2 ** 31

    text = import_model(model, act)
    try:
        outputs, _ = compile_and_run(cim_opt, cim_run, None, None,
                                     placement=placement, source=text)
    except PipelineError as err:
        pytest.fail(f"the imported batched model failed to compile or run: {err}")

    assert np.array_equal(np.asarray(outputs), want), (
        f"compiled output {list(outputs)} != ONNX reference {want.tolist()} "
        f"for M={m} K={k} N={n} placement={placement}")


def test_a_wrong_weight_would_actually_be_caught(cim_opt, cim_run):
    # Anti-vacuity, mirroring test_numerical_differential.py's own
    # test_a_wrong_answer_would_actually_fail: if the comparison above
    # could pass regardless of the numbers, it proves nothing. Perturb one
    # weight and require both sides to move together, and to move at all.
    weight, act = _weights_and_act(8, 12, SEED)
    base = onnx_reference_eval(matmul_integer_model(weight), act)

    bumped = weight.copy()
    bumped[0, 0] = np.int8(int(bumped[0, 0]) ^ 0x5A)
    model = matmul_integer_model(bumped)
    want = onnx_reference_eval(model, act)
    assert not np.array_equal(base, want), "the perturbation changed nothing"

    outputs, _ = compile_and_run(cim_opt, cim_run, None, None,
                                 source=import_model(model, act))
    assert np.array_equal(np.asarray(outputs), want)


def test_placement_does_not_change_the_numbers_on_an_imported_model(cim_opt,
                                                                    cim_run):
    # The project's non-negotiable invariant -- placement is an
    # optimization and may never change a value -- asserted for the first
    # time about IR that came out of a model file rather than out of a
    # string builder in this repository.
    weight, act = _weights_and_act(12, 8, SEED)
    text = import_model(matmul_integer_model(weight), act)

    plain, plain_profile = compile_and_run(cim_opt, cim_run, None, None,
                                           source=text, placement=False)
    placed, placed_profile = compile_and_run(cim_opt, cim_run, None, None,
                                             source=text, placement=True)

    assert np.array_equal(np.asarray(plain), np.asarray(placed))
    if "programs" in plain_profile and "programs" in placed_profile:
        assert placed_profile["programs"] <= plain_profile["programs"], (
            "placement emitted MORE weight programs than not running it")


def test_checked_in_lit_fixture_is_current():
    """test/Transforms/onnx-imported-matmul.mlir must still be what the
    importer produces.

    That file is checked in so the `mlir` CI job -- which installs no ONNX
    packages and skips everything else here -- still guards the shape the
    importer emits. A checked-in artifact that nothing regenerates is a
    fixture that silently rots, so this regenerates it and compares the
    body.
    """
    weight = np.array(
        [[1, -2, 3, -4, 5, -6, 7, -8], [9, -10, 11, -12, 13, -14, 15, -16],
         [17, -18, 19, -20, 21, -22, 23, -24],
         [25, -26, 27, -28, 29, -30, 31, -32]], dtype=np.int8)
    act = np.array([2, -3, 5, -7], dtype=np.int8)

    text = import_model(matmul_integer_model(weight), act)
    # Drop the provenance header: it records absolute paths and a model
    # hash, neither of which belongs in a checked-in file.
    body = "\n".join(line for line in text.splitlines()
                     if not line.startswith("//"))

    fixture = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "Transforms", "onnx-imported-matmul.mlir")
    with open(fixture) as handle:
        checked_in = "\n".join(
            line for line in handle.read().splitlines()
            if not line.startswith("//") and line.strip())

    assert body.strip() == checked_in.strip(), (
        f"{fixture} is stale: regenerate it from the importer.\n"
        f"--- importer now emits ---\n{body}\n"
        f"--- checked in ---\n{checked_in}")
